config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'
  get "/help", to:'staticpages#help'
  get "/contact", to:'staticpages#contact'
  get "/about", to:"staticpages#about"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  before_save {email.downcase!}
  has_secure_password
  AAA = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,  presence:true, length: {maximum: 255},
              uniqueness:true, format: {with: AAA}
  validates :password, presence:true, length: {minimum: 6}
  validates :name, presence:true, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_params, only: [:create]
  def new
  end

  def create
    @user = User.new(email: params[:email], 
          password: params[:password], name: params[:name])
    if @user.save
      flash[:success]="success"
      redirect_to root_path
    else 
      flash[:danger]="faild"
      redirect_to new_user_path
    end
  end

  private
    def user_params
      params.permit(:name, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title="")
        base_title = "Ruby on Rails"
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home",   root_path %></li>
                <li><%= link_to "Help",   help_path %></li>
                <li><%= link_to "Log in", new_user_path %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if !flash.empty? %>
      <%= flash.each {|i| puts i} %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/staticpages/about.html.erb
<%= provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/screencast">screencast</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/staticpages/contact.html.erb
<%= provide(:title, "Contact") %>
<h1>Staticpages#contact</h1>
<p>Find me in app/views/staticpages/contact.html.erb</p>

app/views/staticpages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial Help page</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/staticpages/home.html.erb
<%= provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
                      "https://rubyonrails.org/" %>

app/views/users/new.html.erb
<%= form_with url: users_path do |f| %>
  <%= f.text_field :name %> 
  <%= f.email_field :email %>
  <%= f.password_field :password %>
  <%= f.submit "送信" %>
<% end %>